# fly.toml app configuration file generated for fly-manga-reader on 2026-03-15T15:37:16+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fly-manga-reader'
primary_region = 'ams'

[build]

[env]
  MONGO_DB = 'manga-reader-database'
  NODE_ENV = 'production'
  ONEDRIVE_BASE_PATH = '/DMS/S3-mangago-bucket'
  PORT = '3000'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
